### ISSUE TITLE
custom labels and custom querysets with Django autocomplete_fields?

### ISSUE THREAD

**Issue by kakulukia** [codingjoe/django-select2#13]
I had a look at the current state of autocomplete_fields and i sadly fail to see how they all of a sudden are superior to this package which worked quite nice in my Django 2.1.5 admin, which im trying to upgrade.

My project uses django-select2 to have custom labels and custom querysets. 
While i can work my way around some of that stuff, it gets kinda crazy once i want different restrictions for the same model used in different relations.

By claiming: "Autocomplete fields are superior and we recommend using them, instead of this package for the admin." this should be possible somehow and @codingjoe i bet you know how? Could you point me in the right direction?

Why was the Admin supported removed in the first place?

**Comment by codingjoe** [comment]
Hi @kakulukia,

Thanks for reaching out. Let me try to give you a little more context on the current situation and how it came to be.
First of, there was never official support for Django admin but it worked. That is the same as today, where we don't officially support it, but it works. In fact, I have used this package in Django admin myself.

The recommendation comes for the fact, that I implemented Django's `autocomplete_fields` and it's simpler and implemented more custom to Django's admin and therefore does not require any setup, like the cache setup.

I guess the wording can be misleading. But, and this is important, I will not accept any feature requests for Django admin, since I don't want to maintain two implementations of the same thing. If you are missing a feature in Django's I rather put my time and effort into implementing it in Django. That being said, you are most welcome to review my select2 related patch on Django to get it into the next release: https://github.com/django/django/pull/11026

If you are having any particular issues or questions regarding the integration (even in Django admin) I am happy to assist you.

Best,
Joe

PS: Since this seems to be related to a commercial project, becoming a sponsor is known to increase the level of detain in my responses.
