### ISSUE TITLE
Regenerate documentation on readthedocs.io

### ISSUE THREAD

**Issue by sdolemelipone** [codingjoe/django-select2#141]
I recently upgraded from 7.6 to 7.10 but ran into some issues due to the new `THEME` option introduced in 7.9.0. I've figured the problem out now, but having up to date documentation would have been really useful.

It looks like the documenation on readthedocs.io hasn't been regenerated for some time. Would you be able to regenerate it?
Thanks.

**Comment by codingjoe** [comment]
Hi @sdolemelipone,

Thanks for reaching out. The docs have been generated for all releases, including the latest.
After inspecting the build logs, it seems there were errors due to the old Python used to build the docs. I believe we need to add a rtfd config file to update the version and everything should work just fine.

I'll open a PR.

Best Joe
