### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by DmytroLitvinov** [codingjoe/django-select2#84]
Hi @codingjoe ,

Thank you that you took the maintenance of the package.
A have a general question related to major upgrade.
We are using django-select2@6 and we want to upgrade to django-select2@7 ([the latest version from PyPI](https://pypi.org/project/django-select2/)) and I did not found any changelog file so we can do upgrade.

Can we have changelog for that package or maybe if you don't mind sharing some thoughts, ideas before we start to upgrade. At what we should pay attention to.

Thank you for your attention to this matter

**Comment by codingjoe** [comment]
Hi @DmytroLitvinov,

Thank you for reaching out. We switched to documenting out changes on the GitHub releases instead of a change log file a while ago. That being said, the breaking change in v7 was very minor. We simply added a `request` argument to the `filter_queryset` method of model select inputs, see also https://github.com/codingjoe/django-select2/commit/ffe91627d8befbf6fdf8798cbda572b4c6c3cced

Since you asked for my thoughts: It's a lot of work to maintain a good change log file, not only for me, but it's a barrier for every new contributor. I also think it's not really needed since Git, if you write good messages, can be an excellent change log because it literally contains the changes. We use the release notes, to not essential updates or update specific instructions.
Should you use a tool like dependabot to keep you dependencies up to date, you will find that those tools actually work very well, with this workflow.

I hope this answer helps you.

Best,
Joe
